import { useEffect, useMemo, useState } from "react";
import { base100Series, comparisonMetrics, relativePosition, synchronizedBenchmarkReturn } from "./comparison-engine";
import { formatCompactMoney, formatMoney, formatNumber, formatPercent } from "./formatters";
import { classifySector } from "./sector-classification";
import AssetSearch from "./AssetSearch.jsx";
import "./ComparisonPage.css";

const DATA_URL="https://raw.githubusercontent.com/sylenovitorr-ux/b3-score-dados/main/data/benchmarks.json",SELIC_URL="https://api.bcb.gov.br/dados/serie/bcdata.sgs.1178/dados/ultimos/400?formato=json";
const FIELDS=[["score","Score",true,(v)=>formatNumber(v,0)],["pe","P/L",false,formatNumber],["pb","P/VP",false,formatNumber],["roe","ROE",true,(v)=>formatPercent(v,false)],["growth","Cresc. receita",true,formatPercent],["debt","Dívida/EBITDA",false,formatNumber],["dividendYield","DY",true,(v)=>formatPercent(v,false)],["momentum20","Retorno 20 pregões",true,formatPercent],["volume","Liquidez",true,formatCompactMoney]];
const d=(x)=>x?new Date(`${x}T12:00:00`).toLocaleDateString("pt-BR"):"N/D";
function PerformanceChart({assets,anomalies}){const colors=["#087a45","#25638c","#b56b16","#8b4f9f"];const lines=assets.map((asset,index)=>({asset,color:colors[index],rows:base100Series(anomalies?.assets?.[asset.ticker]?.series??[]).slice(-126)})).filter((x)=>x.rows.length>1);if(!lines.length)return <div className="v2-unavailable-box"><b>Gráfico indisponível</b><span>As séries históricas B3 ainda não têm duas sessões para os ativos selecionados.</span></div>;const all=lines.flatMap((x)=>x.rows.map((r)=>r.value)),min=Math.min(...all),max=Math.max(...all),span=max-min||1;const points=(rows)=>rows.map((r,i)=>`${28+i/Math.max(1,rows.length-1)*704},${230-(r.value-min)/span*190}`).join(" ");return <section className="v2-chart-card"><div className="v2-section-title"><span>GRÁFICO COMPARATIVO</span><h2>Performance normalizada — últimos 126 pregões</h2><p>Todos iniciam em 100. O gráfico compara retorno, não preço nominal.</p></div><figure className="v2-comparison-chart"><svg viewBox="0 0 760 260" role="img" aria-label="Performance normalizada dos ativos selecionados">{[0,1,2,3,4].map((i)=><line key={i} x1="28" x2="732" y1={40+i*47.5} y2={40+i*47.5}/>)}{lines.map((line)=><polyline key={line.asset.ticker} points={points(line.rows)} style={{stroke:line.color}}/>)}</svg><figcaption>{lines.map((line)=><span key={line.asset.ticker}><i style={{background:line.color}}/>{line.asset.ticker} <b>{formatNumber(line.rows.at(-1).value,1)}</b></span>)}</figcaption></figure></section>;}
function valid(a,anomalies){const m=comparisonMetrics(a,anomalies?.assets?.[a.ticker]);return Boolean(a.fundamentals||a.fund)&&[m.score,m.pb,m.roe].filter((x)=>x!==null).length>=2&&Boolean(classifySector(a).label);}
function selic(rows=[]){let n=100;const series=rows.map((r)=>{const v=Number(String(r.valor??"").replace(",",".")),date=r.data?.split("/").reverse().join("-");if(!Number.isFinite(v)||!date)return null;n*=(1+v/100)**(1/252);return {date,value:v,base100:+n.toFixed(6)};}).filter(Boolean);return {id:"SELIC",name:"Selic acumulada",status:series.length?"ATUALIZADO":"INDISPONÍVEL",source:"Banco Central — SGS 1178",referenceDate:series.at(-1)?.date??null,series};}
function Benchmarks({asset,anomaly,data}){const prices=anomaly?.assets?.[asset.ticker]?.series??[];const rows=Object.values(data?.series??{}).map((b)=>({...b,r:synchronizedBenchmarkReturn(prices,b.series)})).filter((b)=>b.r.available);return <section className="v2-benchmark-panel"><div className="v2-section-title"><span>BENCHMARKS OFICIAIS</span><h2>Ativo versus mercado</h2><p>Retorno relativo na mesma janela, sem inventar pregões.</p></div><div className="v2-benchmark-grid">{rows.map((b)=><article key={b.id}><header><b>{b.id}</b><span>{b.status}</span></header><strong>{formatPercent(b.r.relativeReturnPct)}</strong><small>ativo {formatPercent(b.r.assetReturnPct)} • {b.name} {formatPercent(b.r.benchmarkReturnPct)}</small><em>{b.r.sessions} sessões • {d(b.r.startDate)} a {d(b.r.endDate)}</em></article>)}</div></section>;}
export default function ComparisonPage({assets,anomalies,benchmarks,onBack,onOpen}){
 const eligible=useMemo(()=>assets.filter((a)=>valid(a,anomalies)),[assets,anomalies]);const groups=useMemo(()=>eligible.reduce((m,a)=>{const key=classifySector(a).label;m.set(key,[...(m.get(key)??[]),a]);return m;},new Map()),[eligible]);const sectors=useMemo(()=>[...groups.entries()].filter(([,a])=>a.length>=2).sort((a,b)=>a[0].localeCompare(b[0])),[groups]);
 const [sector,setSector]=useState(""),[ticks,setTicks]=useState([]),[data,setData]=useState(benchmarks??null);const candidates=groups.get(sector)??[];const selected=ticks.map((t)=>eligible.find((a)=>a.ticker===t)).filter(Boolean);const lead=selected[0];
 useEffect(()=>{const load=(p)=>fetch(SELIC_URL).then((r)=>r.ok?r.json():null).then((rows)=>setData({...p,series:{...p.series,SELIC:selic(rows??[])}})).catch(()=>setData(p));if(benchmarks?.series)load(benchmarks);else fetch(DATA_URL).then((r)=>r.ok?r.json():null).then((p)=>p?.series&&load(p));},[benchmarks]);
 const choose=(ticker)=>setTicks((old)=>old.includes(ticker)?old.filter((x)=>x!==ticker):old.length<4?[...old,ticker]:old);const chooseAsset=(asset)=>{const nextSector=classifySector(asset).label;if(!sector)setSector(nextSector);choose(asset.ticker);};const changeSector=(next)=>{setSector(next);setTicks([]);};
 return <div className="v2-page"><header className="v2-page-head"><button onClick={onBack}>← Início</button><div><span>COMPARAÇÃO POR SETOR</span><h1>Compare somente pares elegíveis</h1><p>O app mostra apenas empresas com setor definido e dados fundamentais mínimos para a comparação.</p></div></header>
 <section className="v2-company-picker typed-comparison"><div><AssetSearch assets={sector?candidates:eligible} excludeTickers={ticks} onSelect={chooseAsset} label={sector?"Adicionar outro ativo do mesmo setor":"1. Digite o primeiro ativo"} placeholder="PETR4F, BPAC11F, HGLG11 ou nome" fractionalSymbols/><span>{ticks.length}/4 selecionados{sector?` · ${sector}`:""}</span></div>{ticks.length>0&&<div className="v2-selected-assets">{selected.map((asset)=><button key={asset.ticker} onClick={()=>choose(asset.ticker)}><b>{asset.ticker}</b><span>{asset.name}</span><i>×</i></button>)}</div>}</section>
 <section className="v2-sector-select"><label>Ou filtre primeiro pelo setor<select value={sector} onChange={(e)=>changeSector(e.target.value)}><option value="">Todos os setores comparáveis</option>{sectors.map(([name,list])=><option key={name} value={name}>{name} — {list.length} empresas com dados comparáveis</option>)}</select></label>{sector&&<div><b>{candidates.length} empresas com dados comparáveis em {sector}</b><span>A busca oferece somente pares desse mesmo setor.</span></div>}</section>
 {!lead?<div className="v2-empty"><b>Digite e selecione ao menos um ativo.</b><span>Ao escolher o primeiro, o app limita as próximas opções aos pares comparáveis do mesmo setor.</span></div>:<><PerformanceChart assets={selected} anomalies={anomalies}/><section className="v2-compare-table"><div className="v2-compare-row head"><span>Indicador</span>{selected.map((a)=><button key={a.ticker} onClick={()=>onOpen(a.ticker)}>{a.ticker}<small>{formatMoney(a.price)}</small></button>)}</div>{FIELDS.map(([key,label,higher,fmt])=><div className="v2-compare-row" key={key}><span>{label}<small>{higher?"maior tende a ser melhor":"menor exige contexto"}</small></span>{selected.map((a)=>{const v=comparisonMetrics(a,anomalies?.assets?.[a.ticker])[key];return <b key={a.ticker}>{v===null?"N/D":fmt(v)}</b>})}</div>)}</section><section className="v2-sector"><div className="v2-section-title"><span>MEDIANA DO SETOR</span><h2>{sector}</h2><p>{candidates.length} empresas com dados comparáveis.</p></div><div>{[["pe","P/L",false],["pb","P/VP",false],["roe","ROE",true],["score","Score",true]].map(([key,label,hi])=>{const p=relativePosition(comparisonMetrics(lead,anomalies?.assets?.[lead.ticker])[key],candidates.map((a)=>comparisonMetrics(a,anomalies?.assets?.[a.ticker])[key]),hi);return <article key={key}><span>{label}</span><b>{p.available?formatNumber(p.median):"N/D"}</b><small>{p.available?`posição ${p.rank}/${p.total}`:"dados insuficientes"}</small></article>})}</div></section><Benchmarks asset={lead} anomaly={anomalies} data={data}/></>}</div>;
}
