import { useEffect, useMemo, useState } from "react";
import { comparisonMetrics, relativePosition, synchronizedBenchmarkReturn } from "./comparison-engine";
import { formatCompactMoney, formatMoney, formatNumber, formatPercent } from "./formatters";
import { classifySector } from "./sector-classification";

const BENCHMARK_URL="https://raw.githubusercontent.com/sylenovitorr-ux/b3-score-dados/main/data/benchmarks.json";
const SELIC_URL="https://api.bcb.gov.br/dados/serie/bcdata.sgs.1178/dados/ultimos/400?formato=json";
const METRICS=[["score","Score",true,(v)=>formatNumber(v,0)],["confidence","Confiança",true,(v)=>formatPercent(v,false)],["pe","P/L",false,formatNumber],["pb","P/VP",false,formatNumber],["roe","ROE",true,(v)=>formatPercent(v,false)],["growth","Cresc. receita",true,formatPercent],["debt","Dívida/EBITDA",false,formatNumber],["dividendYield","Dividend yield",true,(v)=>formatPercent(v,false)],["momentum20","Retorno 20 pregões",true,formatPercent],["volatility","Volatilidade a.a.",false,(v)=>formatPercent(v,false)],["volume","Liquidez",true,formatCompactMoney]];
const date=(value)=>value?new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR"):"Dado indisponível";
function selic(rows=[]){let level=100;const series=rows.map((row)=>{const value=Number(String(row.valor??"").replace(",", "."));const d=row.data?.split("/").reverse().join("-");if(!Number.isFinite(value)||!d)return null;level*=(1+value/100)**(1/252);return {date:d,value,base100:Number(level.toFixed(6))};}).filter(Boolean).sort((a,b)=>a.date.localeCompare(b.date));return {id:"SELIC",name:"Selic acumulada",status:series.length?"ATUALIZADO":"INDISPONÍVEL",source:"Banco Central do Brasil — SGS 1178",referenceDate:series.at(-1)?.date??null,series,normalization:"100 × produto((1 + Selic anual/100)^(1/252))",limitation:"Acumulação teórica; CDI é a referência interbancária efetiva."};}
function Benchmarks({asset,anomaly,benchmarks}){const prices=anomaly?.assets?.[asset.ticker]?.series??[];const rows=Object.values(benchmarks?.series??{}).map((x)=>({...x,result:synchronizedBenchmarkReturn(prices,x.series)})).filter((x)=>x.result.available);return <section className="v2-benchmark-panel"><div className="v2-section-title"><span>BENCHMARKS OFICIAIS</span><h2>Retorno na mesma janela</h2><p>Ativo menos benchmark, sem preencher pregões ausentes.</p></div>{rows.length?<div className="v2-benchmark-grid">{rows.map((x)=><article key={x.id}><header><b>{x.id}</b><span>{x.status}</span></header><strong>{formatPercent(x.result.relativeReturnPct)}</strong><small>ativo {formatPercent(x.result.assetReturnPct)} • {x.name} {formatPercent(x.result.benchmarkReturnPct)}</small><em>{x.result.sessions} sessões • {date(x.result.startDate)} a {date(x.result.endDate)}</em><i>{x.source} • {date(x.referenceDate)}</i></article>)}</div>:<div className="v2-unavailable-box"><b>Sincronização insuficiente</b><span>São exigidos dois pregões idênticos entre ativo e referência.</span></div>}</section>;}
export default function ComparisonPage({assets,anomalies,benchmarks,onBack,onOpen}){
 const [tickers,setTickers]=useState(()=>{try{return JSON.parse(localStorage.getItem("b3-score-comparison-v1")??"[]").slice(0,4)}catch{return[]}}),[candidate,setCandidate]=useState(""),[group,setGroup]=useState(null),[data,setData]=useState(benchmarks??null);
 useEffect(()=>localStorage.setItem("b3-score-comparison-v1",JSON.stringify(tickers)),[tickers]);
 useEffect(()=>{const attach=(p)=>fetch(SELIC_URL,{cache:"no-store"}).then((r)=>r.ok?r.json():null).then((rows)=>setData({...p,series:{...p.series,SELIC:selic(rows??[])}})).catch(()=>setData(p));if(benchmarks?.series)attach(benchmarks);else fetch(BENCHMARK_URL,{cache:"no-store"}).then((r)=>r.ok?r.json():null).then((p)=>p?.series&&attach(p));},[benchmarks]);
 const groups=useMemo(()=>assets.reduce((m,a)=>{const label=classifySector(a).label??(a.kind==="fii"?"FIIs sem segmento":"Sem classificação oficial");m.set(label,[...(m.get(label)??[]),a]);return m;},new Map()),[assets]);
 const choices=[...groups.entries()].filter(([,v])=>v.length>=2).sort((a,b)=>a[0].localeCompare(b[0]));const selected=tickers.map((t)=>assets.find((a)=>a.ticker===t)).filter(Boolean);const lead=selected[0];const sector=lead?classifySector(lead):null;const peers=sector?.label?groups.get(sector.label)??[]:[];
 const add=()=>{const t=candidate.toUpperCase();if(assets.some((a)=>a.ticker===t)&&!tickers.includes(t)&&tickers.length<4)setTickers([...tickers,t]);setCandidate("");};const choose=(name)=>{setGroup(name);setTickers((groups.get(name)??[]).slice(0,4).map((a)=>a.ticker));};
 return <div className="v2-page"><header className="v2-page-head"><button onClick={onBack}>← Início</button><div><span>COMPARAÇÃO POR SETOR</span><h1>Comparar pares de verdade</h1><p>Escolha o setor: o app carrega até quatro empresas do mesmo grupo.</p></div></header><section className="v2-sector-picker"><div><span>1. ESCOLHA O SETOR</span><h2>Grupos econômicos</h2><p>Setor B3 oficial tem prioridade. Grupos inferidos ficam identificados e não usam segmentos de governança.</p></div><div className="v2-sector-buttons">{choices.map(([name,list])=><button key={name} className={group===name?"active":""} onClick={()=>choose(name)}><b>{name}</b><span>{list.length} ativos</span></button>)}</div></section><section className="v2-picker"><label>2. Adicionar manualmente<input list="compare-assets" value={candidate} onChange={(e)=>setCandidate(e.target.value.toUpperCase())} onKeyDown={(e)=>e.key==="Enter"&&add()} placeholder="PETR4"/><datalist id="compare-assets">{assets.map((a)=><option key={a.ticker} value={a.ticker}>{a.name}</option>)}</datalist></label><button onClick={add} disabled={!candidate||tickers.length>=4}>Adicionar</button><div>{selected.map((a)=><button key={a.ticker} onClick={()=>setTickers(tickers.filter((t)=>t!==a.ticker))}>{a.ticker} ×</button>)}</div></section>{!lead?<div className="v2-empty"><b>Escolha um grupo acima.</b><span>Os pares serão carregados automaticamente.</span></div>:<><section className="v2-compare-table"><div className="v2-compare-row head"><span>Indicador</span>{selected.map((a)=><button key={a.ticker} onClick={()=>onOpen(a.ticker)}>{a.ticker}<small>{formatMoney(a.price)}</small></button>)}</div>{METRICS.map(([key,label,higher,fmt])=><div className="v2-compare-row" key={key}><span>{label}<small>{higher?"maior tende a ser melhor":"menor exige contexto"}</small></span>{selected.map((a)=><b key={a.ticker}>{comparisonMetrics(a,anomalies?.assets?.[a.ticker])[key]===null?"Dado indisponível":fmt(comparisonMetrics(a,anomalies?.assets?.[a.ticker])[key])}</b>)}</div>)}</section><section className="v2-sector"><div className="v2-section-title"><span>REFERÊNCIA DO GRUPO</span><h2>{sector?.label??"Sem setor verificável"}</h2><p>{peers.length} ativos no grupo • {sector?.official?"fonte oficial":"classificação inferida; confirme a atividade"}</p></div>{sector?.label&&<div>{[["pe","P/L",false],["pb","P/VP",false],["roe","ROE",true],["score","Score",true]].map(([key,label,higher])=>{const pos=relativePosition(comparisonMetrics(lead,anomalies?.assets?.[lead.ticker])[key],peers.map((p)=>comparisonMetrics(p,anomalies?.assets?.[p.ticker])[key]),higher);return <article key={key}><span>{label}</span><b>{pos.available?formatNumber(pos.median):"N/D"}</b><small>{pos.available?`mediana • posição ${pos.rank}/${pos.total}`:"dados insuficientes"}</small></article>})}</div>}</section><Benchmarks asset={lead} anomaly={anomalies} benchmarks={data}/></>}</div>;
}
