import { useMemo, useState } from "react";
import { formatMoney, formatNumber, formatPercent } from "./formatters";
import { positionSizing, simulateTrade } from "./quant/trade-simulator-engine";

const numeric = (value) => Number.isFinite(Number(value)) ? Number(value) : null;
const Field = ({ label, children }) => <label>{label}{children}</label>;

function ActionSimulator({ assets }) {
  const stocks = assets.filter((asset) => asset.kind !== "fii");
  const [form, setForm] = useState({ ticker: "BBSE3", capital: "10000", riskPct: "1", entry: "", target: "", stop: "", operation: "common", brokerageBuy: "0", brokerageSell: "0", b3FeesBuy: "", b3FeesSell: "", monthlySales: "" });
  const asset = stocks.find((item) => item.ticker === form.ticker) ?? stocks[0];
  const set = (key, value) => setForm({ ...form, [key]: value });
  const entry = numeric(form.entry) || asset?.price;
  const sizing = useMemo(() => positionSizing({ capital: numeric(form.capital), riskPct: numeric(form.riskPct), entry, stop: numeric(form.stop), maxPositionPct: 15 }), [form.capital, form.riskPct, form.stop, entry]);
  const trade = useMemo(() => sizing.available && numeric(form.target) ? simulateTrade({ assetType: "stock", operation: form.operation, quantity: sizing.quantity, buyPrice: entry, sellPrice: numeric(form.target), brokerageBuy: numeric(form.brokerageBuy) ?? 0, brokerageSell: numeric(form.brokerageSell) ?? 0, b3FeesBuy: form.b3FeesBuy === "" ? null : numeric(form.b3FeesBuy), b3FeesSell: form.b3FeesSell === "" ? null : numeric(form.b3FeesSell), monthlySales: form.monthlySales === "" ? null : numeric(form.monthlySales) }) : null, [sizing, form, entry]);
  return <section className="v2-simulator">
    <div className="v2-form-grid">
      <Field label="Ativo"><select value={asset?.ticker ?? ""} onChange={(e) => { const next = stocks.find((a) => a.ticker === e.target.value); setForm({ ...form, ticker: e.target.value, entry: next?.price ? String(next.price) : "" }); }}>{stocks.map((item) => <option key={item.ticker} value={item.ticker}>{item.ticker}</option>)}</select></Field>
      <Field label="Capital"><input type="number" value={form.capital} onChange={(e) => set("capital", e.target.value)} /></Field><Field label="Risco por operação (%)"><input type="number" step="0.1" value={form.riskPct} onChange={(e) => set("riskPct", e.target.value)} /></Field><Field label="Entrada"><input type="number" value={form.entry} placeholder={asset?.price ? String(asset.price) : "N/D"} onChange={(e) => set("entry", e.target.value)} /></Field><Field label="Alvo"><input type="number" value={form.target} onChange={(e) => set("target", e.target.value)} /></Field><Field label="Stop"><input type="number" value={form.stop} onChange={(e) => set("stop", e.target.value)} /></Field><Field label="Operação"><select value={form.operation} onChange={(e) => set("operation", e.target.value)}><option value="common">Comum</option><option value="day_trade">Day trade</option></select></Field><Field label="Corretagem compra"><input type="number" value={form.brokerageBuy} onChange={(e) => set("brokerageBuy", e.target.value)} /></Field><Field label="Corretagem venda"><input type="number" value={form.brokerageSell} onChange={(e) => set("brokerageSell", e.target.value)} /></Field><Field label="Taxa B3 compra"><input type="number" placeholder="informe a nota" value={form.b3FeesBuy} onChange={(e) => set("b3FeesBuy", e.target.value)} /></Field><Field label="Taxa B3 venda"><input type="number" placeholder="informe a nota" value={form.b3FeesSell} onChange={(e) => set("b3FeesSell", e.target.value)} /></Field><Field label="Vendas de ações no mês"><input type="number" placeholder="necessário para isenção" value={form.monthlySales} onChange={(e) => set("monthlySales", e.target.value)} /></Field>
    </div>
    {sizing.available ? <><div className="v2-sim-results">{[["Quantidade máxima", sizing.quantity], ["Valor da posição", formatMoney(sizing.positionValue)], ["Risco por ação", formatMoney(sizing.riskPerShare)], ["Perda se stop", formatMoney(sizing.estimatedLoss)], ["Peso da posição", formatPercent(sizing.positionPct, false)], ["Resultado final estimado", trade?.values.netFinal == null ? "Dados insuficientes" : formatMoney(trade.values.netFinal)]].map(([label, value]) => <article key={label}><span>{label}</span><b>{value}</b></article>)}</div><p className="v2-method-note">{sizing.formula}</p>{trade && <details className="quant-trace"><summary><span>Impostos e taxas</span><b>Como é calculado?</b><i>⌄</i></summary><div><p>Compra: <b>{formatMoney(trade.values.buy)}</b> • Venda: <b>{formatMoney(trade.values.sell)}</b> • Resultado antes do IR: <b>{formatMoney(trade.values.netBeforeTax)}</b>.</p><p>IRRF: <b>{formatMoney(trade.values.irrf)}</b> • IR apurado: <b>{trade.values.grossTax == null ? "Dados insuficientes" : formatMoney(trade.values.grossTax)}</b> • IR restante: <b>{trade.values.taxRemaining == null ? "Dados insuficientes" : formatMoney(trade.values.taxRemaining)}</b>.</p><p><b>Regra:</b> {trade.rule.source} • verificada em {trade.rule.verifiedAt} • alíquota {formatPercent(trade.rule.rate * 100, false)}.</p><p><b>Limitação:</b> {trade.limitation}</p></div></details>}</> : <p className="v2-empty">Informe entrada e stop abaixo da entrada. Nenhum valor ausente é substituído por zero.</p>}
  </section>;
}

function FiiSimulator({ assets }) { const fiis = assets.filter((asset) => asset.kind === "fii" && asset.fund); const [ticker, setTicker] = useState(""), [capital, setCapital] = useState("10000"), [months, setMonths] = useState("12"); const asset = fiis.find((item) => item.ticker === ticker) ?? fiis[0]; const amount = numeric(capital), period = numeric(months), dy = numeric(asset?.fund?.dy12); const quantity = amount && asset?.price ? Math.floor(amount / asset.price) : null; const income = quantity !== null && dy !== null && period !== null ? quantity * asset.price * (dy / 100) * (period / 12) : null; return <section className="v2-simulator"><div className="v2-form-grid three"><Field label="FII"><select value={asset?.ticker ?? ""} onChange={(e) => setTicker(e.target.value)}>{fiis.map((item) => <option key={item.ticker} value={item.ticker}>{item.ticker}</option>)}</select></Field><Field label="Capital"><input type="number" value={capital} onChange={(e) => setCapital(e.target.value)} /></Field><Field label="Prazo em meses"><input type="number" value={months} onChange={(e) => setMonths(e.target.value)} /></Field></div><div className="v2-sim-results">{[["Cotas inteiras", quantity ?? "Dados insuficientes"], ["Preço atual", formatMoney(asset?.price)], ["DY 12m observado", dy === null ? "Dado indisponível" : formatPercent(dy, false)], ["Renda bruta estimada", income === null ? "Dados insuficientes" : formatMoney(income)]].map(([label, value]) => <article key={label}><span>{label}</span><b>{value}</b></article>)}</div><p className="v2-method-note">A projeção usa o DY observado nos últimos 12 meses como premissa explícita. Rendimentos futuros podem mudar.</p></section>; }

export default function SimulatorPage({ assets, onBack, onOptions, portfolio }) { const [mode, setMode] = useState("hub"); if (mode === "portfolio") return <div className="v2-page"><header className="v2-page-head"><button onClick={() => setMode("hub")}>← Simuladores</button><div><span>APORTES E CENÁRIOS</span><h1>Simulador de carteira</h1></div></header>{portfolio}</div>; return <div className="v2-page"><header className="v2-page-head"><button onClick={mode === "hub" ? onBack : () => setMode("hub")}>← {mode === "hub" ? "Início" : "Simuladores"}</button><div><span>FERRAMENTAS ISOLADAS</span><h1>{mode === "hub" ? "O que deseja simular?" : mode === "stock" ? "Posição em ação" : "Renda de FII"}</h1><p>Cada cálculo mostra premissas e mantém dados ausentes como indisponíveis.</p></div></header>{mode === "hub" ? <div className="v2-simulator-hub"><button onClick={() => setMode("stock")}><i>↗</i><b>Ação</b><span>Entrada, stop, posição, impostos e custos</span></button><button onClick={() => setMode("fii")}><i>▥</i><b>FII</b><span>Cotas, DY observado e renda estimada</span></button><button onClick={() => setMode("portfolio")}><i>▦</i><b>Carteira</b><span>Aportes mensais e cenários patrimoniais</span></button><button onClick={onOptions}><i>◉</i><b>Opções</b><span>Payoff, gregas, IV e estratégias</span></button></div> : mode === "stock" ? <ActionSimulator assets={assets} /> : <FiiSimulator assets={assets} />}</div>; }
